### PR TITLE
feat(images-script): Updated Default Skin, Add new effect, Fix few things

### PR DESCRIPTION
**Pull request by AlberttFrgk**

### CODE REVIEW

**Comment by Estrol** [comment]
Do you have any preview on what visual changes on the default skin?

**Comment by AlberttFrgk** [comment]
> Do you have any preview on what visual changes on the default skin?

seems not much, just add new effect and slightly optimize

**Comment by Estrol** [comment]
> > Do you have any preview on what visual changes on the default skin?
> 
> seems not much, just add new effect and slightly optimize

I said is there any preview like image or screenshot?

**Comment by AlberttFrgk** [comment]
> Owner

mostly same, just optimize

**Pull request merged**
